version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: meconnect
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - '3306:3306'  # Map host port 3306 to container port 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - '8080:80'
    networks:
      - app-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27078:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - app-network

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  dbdata6:
  postgres_data:
